# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1d9ea0e18dc4ba2daf7d5bb13fbbfb8a7c72537bd49a39d08c1be1e736c979ca25445c2c2aba1a222e2b0a6ec29e4d74984d4433eae3e24bb0eaacfc6aa46a9d

test:
  secret_key_base: 8c09357d78b8cd8fc06075a5f35d2346a34063ad53dca6b16965232e46f1a0d224c4bea5f51aaa1f82956316bb34cf82746885dbda9c7ed3eac8ed8c16ae92d6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
